# Generated by Django 5.2.4 on 2025-07-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150, verbose_name='Nombre del Visitante')),
                ('visitor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Visitante')),
                ('visitor_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Visitante')),
                ('visitor_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa del Visitante')),
                ('visitor_id_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Identificación')),
                ('visit_type', models.CharField(choices=[('trabajo', 'Trabajo'), ('entrega', 'Entrega'), ('mantenimiento', 'Mantenimiento'), ('reunion', 'Reunión'), ('personal', 'Personal'), ('proveedor', 'Proveedor'), ('otro', 'Otro')], default='trabajo', max_length=15, verbose_name='Tipo de Visita')),
                ('purpose', models.TextField(verbose_name='Propósito de la Visita')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('scheduled_time', models.TimeField(verbose_name='Hora Programada')),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Llegada')),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Salida')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en_progreso', 'En Progreso')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('authorized_by', models.CharField(blank=True, max_length=150, verbose_name='Autorizado por')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('vehicle_plates', models.CharField(blank=True, max_length=20, verbose_name='Placas del Vehículo')),
                ('items_brought', models.TextField(blank=True, verbose_name='Artículos que Trae')),
                ('items_taken', models.TextField(blank=True, verbose_name='Artículos que Se Lleva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visits', to='guards.guard', verbose_name='Aprobado por')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to='guards.guard', verbose_name='Registrado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Inquilino a Visitar')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('arrived', 'Llegó'), ('departed', 'Se Fue'), ('cancelled', 'Cancelada'), ('modified', 'Modificada')], max_length=15, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guards.guard', verbose_name='Realizado por')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='visits.visit', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Registro de Visita',
                'verbose_name_plural': 'Registros de Visitas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
