# Generated by Django 5.2.4 on 2025-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/%Y/%m/%d/', verbose_name='Foto de Identificación'),
        ),
    ]
