# Generated by Django 5.2.4 on 2025-07-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='correo_recepcion',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Recepción de Oficina'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Metros Cuadrados (m²)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='numero_oficina',
            field=models.CharField(default='', max_length=50, verbose_name='Número de Oficina'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='piso',
            field=models.CharField(default='', max_length=50, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razon_social',
            field=models.CharField(default='', max_length=250, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='recibo_luz',
            field=models.TextField(blank=True, help_text='Información adicional sobre el recibo de luz', null=True, verbose_name='Recibo de Luz (Información)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='representante_legal',
            field=models.CharField(default='', max_length=200, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telefono_oficina',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Teléfono de Oficina'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_oficina',
            field=models.CharField(choices=[('privada', 'Oficina Privada'), ('compartida', 'Oficina Compartida'), ('coworking', 'Espacio Coworking'), ('ejecutiva', 'Oficina Ejecutiva'), ('virtual', 'Oficina Virtual'), ('sala_juntas', 'Sala de Juntas')], default='privada', max_length=20, verbose_name='Tipo de Oficina'),
        ),
    ]
