# Generated by Django 5.2.4 on 2025-07-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_electricitybill_maintenanceexpense_tenantaccess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceexpense',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantaccess',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenantannouncement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantincident',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tenantincident',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='tenantincident',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='ElectricityBill',
        ),
        migrations.DeleteModel(
            name='MaintenanceExpense',
        ),
        migrations.DeleteModel(
            name='TenantAccess',
        ),
        migrations.DeleteModel(
            name='TenantAnnouncement',
        ),
        migrations.DeleteModel(
            name='TenantIncident',
        ),
    ]
