# Generated by Django 5.2.4 on 2025-07-19 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Punto')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Punto de Seguridad',
                'verbose_name_plural': 'Puntos de Seguridad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Incidente')),
                ('incident_type', models.CharField(choices=[('acceso_no_autorizado', 'Acceso No Autorizado'), ('robo', 'Robo'), ('vandalismo', 'Vandalismo'), ('emergencia_medica', 'Emergencia Médica'), ('incendio', 'Incendio'), ('falla_equipo', 'Falla de Equipo'), ('comportamiento_sospechoso', 'Comportamiento Sospechoso'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Incidente')),
                ('severity', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('en_investigacion', 'En Investigación'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripción del Incidente')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('incident_datetime', models.DateTimeField(verbose_name='Fecha y Hora del Incidente')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.securitycheckpoint', verbose_name='Punto de Seguridad')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Incidente de Seguridad',
                'verbose_name_plural': 'Incidentes de Seguridad',
                'ordering': ['-incident_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['key'],
            },
        ),
    ]
