# Generated by Django 5.2.4 on 2025-07-21 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Olcha Tecnología En Seguridad', max_length=200, verbose_name='Nombre de la Empresa')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='configuration/logos/', verbose_name='Logo de la Empresa')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='configuration/favicons/', verbose_name='Favicon')),
                ('theme', models.CharField(choices=[('default', 'Azul Corporativo (Por defecto)'), ('green', 'Verde Empresarial'), ('purple', 'Púrpura Moderno'), ('orange', 'Naranja Energético'), ('red', 'Rojo Dinámico'), ('indigo', 'Índigo Profesional'), ('teal', 'Verde Azulado'), ('pink', 'Rosa Creativo')], default='default', max_length=20, verbose_name='Tema del Sistema')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Modo Oscuro')),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido (ej: #FF0000)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Primario')),
                ('secondary_color', models.CharField(default='#0284c7', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido (ej: #FF0000)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Secundario')),
                ('accent_color', models.CharField(default='#0369a1', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido (ej: #FF0000)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de Acento')),
                ('sidebar_color', models.CharField(default='#1e293b', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido (ej: #FF0000)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color del Sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Tema del Sistema',
                'verbose_name_plural': 'Configuraciones de Tema del Sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Modo Oscuro')),
                ('preferred_theme', models.CharField(choices=[('default', 'Azul Corporativo (Por defecto)'), ('green', 'Verde Empresarial'), ('purple', 'Púrpura Moderno'), ('orange', 'Naranja Energético'), ('red', 'Rojo Dinámico'), ('indigo', 'Índigo Profesional'), ('teal', 'Verde Azulado'), ('pink', 'Rosa Creativo')], default='default', max_length=20, verbose_name='Tema Preferido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Tema de Usuario',
                'verbose_name_plural': 'Preferencias de Tema de Usuarios',
            },
        ),
    ]
