# Generated by Django 5.2.4 on 2025-07-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de acción'),
        ),
    ]
