# Generated by Django 5.2.4 on 2025-07-24 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_action_url'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto del botón de acción'),
        ),
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='Color de la notificación'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='fas fa-bell', max_length=50, verbose_name='Icono FontAwesome'),
        ),
        migrations.AddField(
            model_name='notification',
            name='parent_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_action',
            field=models.BooleanField(default=False, verbose_name='Requiere acción del usuario'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('read', 'Leída'), ('dismissed', 'Descartada'), ('archived', 'Archivada')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='thread_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de hilo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('maintenance_request', 'Solicitud de Mantenimiento'), ('maintenance_update', 'Actualización de Mantenimiento'), ('maintenance_completed', 'Mantenimiento Completado'), ('maintenance_rejected', 'Solicitud Rechazada'), ('incident_report', 'Reporte de Incidente'), ('visit_notification', 'Notificación de Visita'), ('visit_approved', 'Visita Aprobada'), ('visit_rejected', 'Visita Rechazada'), ('system_alert', 'Alerta del Sistema'), ('security_alert', 'Alerta de Seguridad'), ('payment_reminder', 'Recordatorio de Pago'), ('general', 'Notificación General'), ('welcome', 'Bienvenida'), ('announcement', 'Anuncio')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Crítica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=3),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='accounts_no_recipie_799191_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['thread_key'], name='accounts_no_thread__66bfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='accounts_no_notific_6d2f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='accounts_no_priorit_230459_idx'),
        ),
    ]
