# Generated by Django 5.2.4 on 2025-07-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_action_text_notification_color_and_more'),
        ('maintenance', '0003_maintenancereport_maintenancereportimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='maintenance_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.maintenancereport', verbose_name='Reporte de mantenimiento relacionado'),
        ),
    ]
