# Generated by Django 5.2.4 on 2025-07-19 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del área')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Piso/Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('area_type', models.CharField(choices=[('estructural', 'Estructural'), ('mecanico', 'Mecánico'), ('electrico', 'Eléctrico'), ('sistemas', 'Sistemas'), ('seguridad', 'Seguridad'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de área')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='Responsable del área')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Información de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Área de Mantenimiento',
                'verbose_name_plural': 'Áreas de Mantenimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación específica')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Piso/Nivel')),
                ('camera_type', models.CharField(choices=[('dome', 'Domo'), ('bullet', 'Bala'), ('ptz', 'PTZ'), ('fisheye', 'Ojo de Pez')], default='dome', max_length=20, verbose_name='Tipo de cámara')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puerto')),
                ('stream_url', models.URLField(blank=True, verbose_name='URL del stream')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='Resolución')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('offline', 'Fuera de línea'), ('maintenance', 'Mantenimiento'), ('inactive', 'Inactiva')], default='active', max_length=20, verbose_name='Estado')),
                ('is_recording', models.BooleanField(default=True, verbose_name='Grabando')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='Última verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='maintenance.maintenancearea', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Cámara de Seguridad',
                'verbose_name_plural': 'Cámaras de Seguridad',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='maintenance.maintenancearea', verbose_name='Área')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Checklist de Mantenimiento',
                'verbose_name_plural': 'Checklists de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Nombre del item')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('skipped', 'Omitido')], default='pending', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.maintenancechecklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Elemento de Checklist',
                'verbose_name_plural': 'Elementos de Checklist',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('before', 'Antes'), ('after', 'Después'), ('problem', 'Problema'), ('solution', 'Solución'), ('progress', 'En Progreso')], max_length=20, verbose_name='Tipo de evidencia')),
                ('image', models.ImageField(upload_to='maintenance/evidences/%Y/%m/', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='maintenance.maintenanceitem', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Evidencia de Mantenimiento',
                'verbose_name_plural': 'Evidencias de Mantenimiento',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
