# Generated by Django 5.2.4 on 2025-07-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('tenants', '0003_electricitybill_maintenanceexpense_tenantaccess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la solicitud')),
                ('category', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('aire_acondicionado', 'Aire Acondicionado'), ('limpieza', 'Limpieza'), ('pintura', 'Pintura'), ('carpinteria', 'Carpintería'), ('cerrajeria', 'Cerrajería'), ('jardineria', 'Jardinería'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción del problema')),
                ('location_details', models.CharField(help_text='Especifica dónde está el problema exactamente', max_length=500, verbose_name='Detalles de ubicación')),
                ('urgency_level', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Nivel de urgencia')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('evidence_file', models.FileField(blank=True, help_text='Foto o documento que ayude a entender el problema', null=True, upload_to='maintenance_requests/evidence/', verbose_name='Archivo de evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas del personal de mantenimiento', verbose_name='Notas administrativas')),
                ('resolution_notes', models.TextField(blank=True, help_text='Descripción de la solución aplicada', verbose_name='Notas de resolución')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo estimado')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo final')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='tenants.tenant', verbose_name='Inquilino')),
            ],
            options={
                'verbose_name': 'Solicitud de Mantenimiento',
                'verbose_name_plural': 'Solicitudes de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
