# Generated by Django 5.2.4 on 2025-07-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Reporte')),
                ('description', models.TextField(verbose_name='Descripción del problema')),
                ('category', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('climatizacion', 'Climatización'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('ascensores', 'Ascensores'), ('jardineria', 'Jardinería'), ('pintura', 'Pintura'), ('carpinteria', 'Carpintería'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('priority', models.IntegerField(choices=[(1, 'Crítica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=3, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('requiere_atencion', 'Requiere Atención'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('specific_location', models.CharField(blank=True, help_text='Ej: Oficina 201, Baño del 3er piso, etc.', max_length=200, verbose_name='Ubicación específica')),
                ('available_times', models.TextField(blank=True, help_text='Indica cuándo es posible acceder al área para realizar el mantenimiento', verbose_name='Horarios disponibles para acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas visibles solo para el equipo de mantenimiento', verbose_name='Notas internas')),
                ('response_to_tenant', models.TextField(blank=True, help_text='Mensaje que será visible para el inquilino', verbose_name='Respuesta al inquilino')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='maintenance.maintenancearea', verbose_name='Área')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte de Mantenimiento',
                'verbose_name_plural': 'Reportes de Mantenimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance_reports/%Y/%m/', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción de la imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenancereport', verbose_name='Reporte')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Imagen de Reporte',
                'verbose_name_plural': 'Imágenes de Reportes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
