# Generated by Django 5.2.4 on 2025-07-19 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID de Empleado')),
                ('position', models.CharField(choices=[('vigilante', 'Vigilante'), ('supervisor', 'Supervisor'), ('jefe_seguridad', 'Jefe de Seguridad')], default='vigilante', max_length=20, verbose_name='Puesto')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('vacaciones', 'Vacaciones')], default='activo', max_length=15, verbose_name='Estado')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('emergency_contact', models.CharField(max_length=150, verbose_name='Contacto de Emergencia')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='Teléfono de Emergencia')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guards/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vigilante',
                'verbose_name_plural': 'Vigilantes',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('matutino', 'Matutino (6:00 - 14:00)'), ('vespertino', 'Vespertino (14:00 - 22:00)'), ('nocturno', 'Nocturno (22:00 - 6:00)')], max_length=15, verbose_name='Tipo de Turno')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.guard', verbose_name='Vigilante')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
