# Generated by Django 5.2.4 on 2025-07-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Punto')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código del Punto')),
                ('point_type', models.CharField(choices=[('entrada_principal', 'Entrada Principal'), ('entrada_secundaria', 'Entrada Secundaria'), ('estacionamiento', 'Estacionamiento'), ('piso', 'Punto de Piso'), ('escalera_emergencia', 'Escalera de Emergencia'), ('azotea', 'Azotea'), ('sotano', 'Sótano'), ('perimetro', 'Perímetro'), ('sala_sistemas', 'Sala de Sistemas'), ('recepcion', 'Recepción')], max_length=25, verbose_name='Tipo de Punto')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación Detallada')),
                ('floor', models.CharField(max_length=20, verbose_name='Piso/Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento')], default='activo', max_length=15, verbose_name='Estado')),
                ('priority', models.IntegerField(default=1, help_text='1=Muy Alta, 2=Alta, 3=Media, 4=Baja, 5=Muy Baja', verbose_name='Prioridad')),
                ('check_frequency_minutes', models.IntegerField(default=60, verbose_name='Frecuencia de Revisión (minutos)')),
                ('qr_code', models.CharField(blank=True, help_text='Código QR para verificación del punto', max_length=100, verbose_name='Código QR')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='security_points/', verbose_name='Foto del Punto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Punto de Seguridad',
                'verbose_name_plural': 'Puntos de Seguridad',
                'ordering': ['priority', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('interrumpido', 'Interrumpido'), ('cancelado', 'Cancelado')], default='iniciado', max_length=15, verbose_name='Estado')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('total_points_checked', models.IntegerField(default=0, verbose_name='Puntos Verificados')),
                ('incidents_reported', models.IntegerField(default=0, verbose_name='Incidentes Reportados')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('weather_conditions', models.CharField(blank=True, max_length=100, verbose_name='Condiciones Climáticas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.guard', verbose_name='Vigilante')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guards.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Rondín de Patrullaje',
                'verbose_name_plural': 'Rondines de Patrullaje',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PointCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(verbose_name='Hora de Verificación')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal'), ('no_verificado', 'No Verificado'), ('no_accesible', 'No Accesible')], default='normal', max_length=15, verbose_name='Estado del Punto')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='point_checks/', verbose_name='Foto de Evidencia')),
                ('qr_verified', models.BooleanField(default=False, verbose_name='QR Verificado')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad (%)')),
                ('patrol_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_checks', to='guards.patrolround', verbose_name='Rondín')),
                ('security_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securitypoint', verbose_name='Punto de Seguridad')),
            ],
            options={
                'verbose_name': 'Verificación de Punto',
                'verbose_name_plural': 'Verificaciones de Puntos',
                'ordering': ['check_time'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('acceso_no_autorizado', 'Acceso No Autorizado'), ('equipo_danado', 'Equipo Dañado'), ('falla_sistema', 'Falla de Sistema'), ('persona_sospechosa', 'Persona Sospechosa'), ('alarma', 'Activación de Alarma'), ('emergencia_medica', 'Emergencia Médica'), ('incendio', 'Incendio'), ('robo', 'Robo'), ('vandalismo', 'Vandalismo'), ('otro', 'Otro')], max_length=25, verbose_name='Tipo de Incidente')),
                ('severity', models.IntegerField(choices=[(1, 'Crítico'), (2, 'Alto'), (3, 'Medio'), (4, 'Bajo'), (5, 'Informativo')], default=3, verbose_name='Severidad')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Incidente')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('actions_taken', models.TextField(blank=True, verbose_name='Acciones Tomadas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/', verbose_name='Foto de Evidencia')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.guard', verbose_name='Vigilante Reporta')),
                ('point_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guards.pointcheck', verbose_name='Verificación de Punto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_resolved', to='guards.guard', verbose_name='Resuelto por')),
                ('security_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securitypoint', verbose_name='Punto de Seguridad')),
            ],
            options={
                'verbose_name': 'Incidente de Seguridad',
                'verbose_name_plural': 'Incidentes de Seguridad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Orden en la Ruta')),
                ('estimated_time_minutes', models.IntegerField(default=5, verbose_name='Tiempo Estimado en el Punto (minutos)')),
                ('security_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securitypoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='guard',
            name='assigned_points',
            field=models.ManyToManyField(blank=True, help_text='Puntos de seguridad específicos asignados', to='guards.securitypoint', verbose_name='Puntos Asignados'),
        ),
        migrations.CreateModel(
            name='SecurityRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Ruta')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código de Ruta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('temporal', 'Temporal')], default='activa', max_length=15, verbose_name='Estado')),
                ('estimated_duration_minutes', models.IntegerField(default=30, verbose_name='Duración Estimada (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('security_points', models.ManyToManyField(through='guards.RoutePoint', to='guards.securitypoint', verbose_name='Puntos de Seguridad')),
            ],
            options={
                'verbose_name': 'Ruta de Seguridad',
                'verbose_name_plural': 'Rutas de Seguridad',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='routepoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securityroute'),
        ),
        migrations.AddField(
            model_name='patrolround',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securityroute', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='guard',
            name='assigned_routes',
            field=models.ManyToManyField(blank=True, help_text='Rutas de rondín asignadas a este vigilante', to='guards.securityroute', verbose_name='Rutas Asignadas'),
        ),
        migrations.AlterUniqueTogether(
            name='routepoint',
            unique_together={('route', 'order')},
        ),
    ]
