# Generated by Django 5.2.4 on 2025-07-24 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenancereport_maintenancereportimage_and_more'),
        ('visits', '0002_visit_visitor_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('visit_approved', 'Visita Aprobada'), ('visit_rejected', 'Visita Rechazada'), ('visit_arrived', 'Visitante Llegó'), ('visit_reminder', 'Recordatorio de Visita'), ('maintenance_assigned', 'Mantenimiento Asignado'), ('maintenance_completed', 'Mantenimiento Completado'), ('emergency_alert', 'Alerta de Emergencia'), ('general_announcement', 'Anuncio General')], max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=200, verbose_name='Plantilla del Título')),
                ('body_template', models.TextField(verbose_name='Plantilla del Mensaje')),
                ('icon_url', models.URLField(blank=True, verbose_name='URL del Icono')),
                ('action_url', models.CharField(blank=True, max_length=200, verbose_name='URL de Acción')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Visitas')),
                ('maintenance_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de Mantenimiento')),
                ('emergency_notifications', models.BooleanField(default=True, verbose_name='Alertas de Emergencia')),
                ('general_notifications', models.BooleanField(default=True, verbose_name='Anuncios Generales')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Inicio Horas Silenciosas')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='Fin Horas Silenciosas')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Activar Horas Silenciosas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida'), ('delivered', 'Entregada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('maintenance_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit')),
            ],
            options={
                'verbose_name': 'Notificación Push',
                'verbose_name_plural': 'Notificaciones Push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(max_length=255, verbose_name='Clave P256DH')),
                ('auth_key', models.CharField(max_length=255, verbose_name='Clave Auth')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
